### PR TITLE
add responsiveness

### PR DESCRIPTION
**Pull request by yyassire**

### CODE REVIEW

**Review by stormcloud266 — CHANGES_REQUESTED** [review]
This is a good idea. Thank you for the PR! I recently merged a different PR, and it looks like there are conflicts with this PR. Can you please make the following changes, and then I will merge:

1. Rebase with the newest main to remove conflicts
2. Remove styles that don't change between screen sizes (like the color in the h1)
3. Remove the padding from the `p` tags (this will be handled once the "add wrapper class" issue is completed)

Thanks again!

**Comment by stormcloud266** [comment]
@yyassire  Looks like you read my mind while I was typing up the review! Please just remove the `p` padding and we will be good to go

**Comment by yyassire** [comment]
Hi 
excuse I was not looking to the conversation board so I did'nt see  your instructions. Removing the padding right await.

**Review by stormcloud266 — APPROVED** [review]
Awesome. Thank you!

**Pull request merged**
