### PR TITLE
#17 added link hover and focus visible

### PR DESCRIPTION
**Pull request by Dhruv1704**
added :hover and :focus-visible styles to a elements in style.css.
with- 

color: #04090c;
background-color: #44bfce;

Also added transition all 0.2s

### CODE REVIEW

**Review by stormcloud266 — CHANGES_REQUESTED** [review]
Thank you for the PR! Since the properties are the same on both selectors, we can use a comma and target both at the same time to save a bit of code.

```css
a:hover,
a:focus-visible {
```

**Comment by Dhruv1704** [comment]
Okay , I will do that.

**Comment by Dhruv1704** [comment]
I have made changes. 
Please review it.

**Review by stormcloud266 — APPROVED** [review]
Looks great!

**Pull request merged**
