### PR TITLE
A new tab

### PR DESCRIPTION
**Pull request by Dhruv1704**
- [x] The Twitter link in the footer should have a target="_blank" and rel="noreferrer" so that it opens in a new tab.

### CODE REVIEW

**Comment by stormcloud266** [comment]
@Dhruv1704  Please update this PR when the requested changes are made in your previous PR, and I will merge. Thank you!

**Comment by Dhruv1704** [comment]
Okay.

**Comment by Dhruv1704** [comment]
I have updated. Please review.
Thank you

**Review by stormcloud266 — APPROVED** [review]
Great job! Thank you

**Pull request merged**
